const KEY='cheiros-da-zu-v1';
const SHEETS_URL='https://script.google.com/macros/s/AKfycbzygLwqiZmKmq6s4t4kS1XchwAn75xNDkn0L7p6jKlVEl9LLIYEU8u-J_AA9tOEh_Mo/exec';
let state=JSON.parse(localStorage.getItem(KEY)||'{"products":[],"sales":[]}');
let period='month';
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function syncStatus(text,kind=''){let el=document.querySelector('#sync-status');if(el){el.textContent=text;el.className=`sync-status ${kind}`}}
function remoteState(data){state={products:(data.produtos||[]).map(p=>({id:Number(p.id),name:p.nome,brand:p.marca,category:p.categoria,price:Number(p.preco),stock:Number(p.estoque)})),sales:(data.vendas||[]).map(s=>({id:Number(s.id),productId:Number(s.produtoId),quantity:Number(s.quantidade),date:String(s.data).slice(0,10),channel:s.canal,customer:s.cliente}))};save();render()}
async function sheetRequest(payload){try{syncStatus('Sincronizando com a planilha…');let options=payload?{method:'POST',body:JSON.stringify(payload)}:{};let response=await fetch(SHEETS_URL,options),data=await response.json();if(!data.ok)throw new Error(data.erro||'Não foi possível sincronizar.');remoteState(data);syncStatus('Planilha conectada', 'ok')}catch(error){console.warn(error);syncStatus('Sem conexão com a planilha', 'error')}}
function sample(){state={products:[
 {id:1,name:'Tododia Ameixa e Flor de Baunilha',brand:'Natura',category:'Hidratante',price:62.9,stock:12},{id:2,name:'Lily Eau de Parfum',brand:'O Boticário',category:'Perfume',price:159.9,stock:3},{id:3,name:'Ekos Castanha Polpa',brand:'Natura',category:'Hidratante',price:49.9,stock:18},{id:4,name:'Nativa SPA Ameixa',brand:'O Boticário',category:'Kit presente',price:89.9,stock:6},{id:5,name:'Kaiak Aventura',brand:'Natura',category:'Perfume',price:119.9,stock:9}],sales:[]};let d=new Date();for(let i=0;i<26;i++){let p=[1,1,1,2,3,3,4,5][i%8],dt=new Date(d);dt.setDate(d.getDate()-(i%24));state.sales.push({id:Date.now()+i,productId:p,quantity:i%5===0?2:1,date:dt.toISOString().slice(0,10),channel:['WhatsApp','Loja física','Instagram'][i%3],customer:i%4?'Cliente recorrente':'Cliente novo'});}save();render();}
function product(id){return state.products.find(p=>p.id===Number(id));}
function filteredSales(){let now=new Date();now.setHours(0,0,0,0);let start=new Date(now);start.setDate(now.getDate()-(period==='week'?6:29));return state.sales.filter(s=>new Date(s.date+'T12:00:00')>=start&&new Date(s.date+'T12:00:00')<=now);}
function aggregate(sales){let m={};sales.forEach(s=>{m[s.productId]=(m[s.productId]||0)+s.quantity});return Object.entries(m).map(([id,q])=>({p:product(id),q})).filter(x=>x.p).sort((a,b)=>b.q-a.q)}
function campaign(){let m=new Date().getMonth()+1;if(m<=2)return {name:'Verão e Carnaval',idea:'autocuidado, fragrâncias leves e presentes rápidos'};if(m===3||m===4)return {name:'Páscoa e renovação',idea:'kits de carinho e rituais de autocuidado'};if(m===5)return {name:'Dia das Mães',idea:'presentes afetivos e kits prontos para entregar'};if(m===6)return {name:'Dia dos Namorados',idea:'perfumaria e kits para presentear'};if(m===8)return {name:'Dia dos Pais',idea:'perfumaria masculina e presentes práticos'};if(m===9)return {name:'Primavera',idea:'novidades, fragrâncias florais e renovação'};if(m===11)return {name:'Black Friday',idea:'combos de maior valor e limpeza de estoque'};return {name:'Natal e fim de ano',idea:'kits presenteáveis e compras antecipadas'};}
function companion(base){let preferred=base.category.toLowerCase().includes('perfume')?['hidrat','sabon','kit']:['perfume','kit','hidrat'];return state.products.filter(p=>p.id!==base.id&&p.stock>0).sort((a,b)=>{let ai=preferred.findIndex(x=>a.category.toLowerCase().includes(x)),bi=preferred.findIndex(x=>b.category.toLowerCase().includes(x));return(ai<0?99:ai)-(bi<0?99:bi)})[0];}
function strategyCard(icon,kind,title,text,detail){return `<article class="strategy-card ${kind}"><span class="card-icon">${icon}</span><h3>${esc(title)}</h3><p>${esc(text)}</p><span class="strategy-detail">${esc(detail)}</span></article>`}
function renderDashboard(){let sales=filteredSales(), orders=sales.length, units=sales.reduce((a,s)=>a+s.quantity,0), revenue=sales.reduce((a,s)=>a+s.quantity*(product(s.productId)?.price||0),0), low=state.products.filter(p=>p.stock<=5).length;document.querySelector('#revenue').textContent=money(revenue);document.querySelector('#units').textContent=units;document.querySelector('#ticket').textContent=money(orders?revenue/orders:0);document.querySelector('#low-stock').textContent=low;document.querySelector('#units-note').textContent=`${orders} ${orders===1?'pedido':'pedidos'} no período`;document.querySelector('#revenue-note').textContent=orders?'com base nas vendas registradas':'Registre ou importe as vendas';document.querySelector('#period-label').textContent=period==='week'?'últimos 7 dias':'últimos 30 dias';let top=aggregate(sales);document.querySelector('#top-products').innerHTML=top.length?top.slice(0,5).map((x,i)=>`<div class="rank"><span class="rank-num">0${i+1}</span><div class="rank-name">${esc(x.p.name)}<small>${esc(x.p.brand)} · ${esc(x.p.category)}</small></div><span class="rank-value">${x.q} un.</span></div>`).join(''):'<p class="empty">Ainda não há vendas neste período.</p>';
let all=aggregate(state.sales), slow=state.products.filter(p=>!all.some(x=>x.p.id===p.id)).sort((a,b)=>b.stock-a.stock)[0], champion=top[0];let st=champion?{t:`Aposte em ${champion.p.name}`,p:`É o produto com maior saída ${period==='week'?'nesta semana':'neste mês'} (${champion.q} unidades). Dê destaque nos status e ofereça uma opção complementar.`,a:`Sugestão: monte um combo com ${champion.p.category.toLowerCase()} e comunique “últimas unidades”.`}:slow?{t:`Dê uma chance para ${slow.name}`,p:`Esse produto ainda não registrou saída e há ${slow.stock} unidades em estoque.`,a:'Sugestão: faça uma demonstração, mostre benefícios e crie uma oferta de combo.'}:{t:'Comece registrando suas vendas',p:'Assim o painel identifica oportunidades e sugere ações para a sua loja.',a:'✦ Sua próxima estratégia aparecerá aqui.'};document.querySelector('#strategy-title').textContent=st.t;document.querySelector('#strategy-text').textContent=st.p;document.querySelector('#strategy-action').textContent=st.a;
let channels={},customers={};sales.forEach(s=>{channels[s.channel]=(channels[s.channel]||0)+1;customers[s.customer]=(customers[s.customer]||0)+1});let mainChannel=Object.entries(channels).sort((a,b)=>b[1]-a[1])[0]?.[0]||'WhatsApp',season=campaign(),kitBase=champion?.p||state.products.find(p=>p.stock>0),kitPair=kitBase&&companion(kitBase),cards=[];if(kitBase&&kitPair){let total=kitBase.price+kitPair.price;cards.push(strategyCard('🎁','kit',`Kit ${kitBase.category} + ${kitPair.category}`,`Una ${kitBase.name} com ${kitPair.name}. A combinação aumenta o valor de cada pedido sem depender só de desconto.`,`Preço normal ${money(total)} · sugestão de kit: ${money(total*.9)} (10% de incentivo).`))}else cards.push(strategyCard('🎁','kit','Monte um kit de estreia','Cadastre pelo menos dois produtos em estoque para o sistema sugerir combinações.','Prefira categorias complementares: perfume + hidratante costuma funcionar bem.'));if(slow)cards.push(strategyCard('🏷️','sale',`Giro para ${slow.name}`,`Há ${slow.stock} unidades sem saída. Evite desconto solto: ofereça o item como complemento de uma compra.`,`Ação: “Na compra de um presente, leve este item com 15% de desconto” por 7 dias.`));else cards.push(strategyCard('🏷️','sale','Promoção com objetivo','Use uma promoção curta, com prazo e estoque limitado, para preservar o valor da marca.','Ação: ofereça entrega ou brinde em compras acima de um valor definido.'));cards.push(strategyCard('📅','season',`Campanha: ${season.name}`,`A época favorece ${season.idea}. Prepare fotos, embalagem e uma lista de presentes em três faixas de preço.`,`Canal prioritário: ${mainChannel}. ${customers['Cliente recorrente']>customers['Cliente novo']?'Convide clientes recorrentes para uma prévia exclusiva.':'Use uma mensagem de boas-vindas e cupom para clientes novas.'}`));document.querySelector('#season-tag').textContent=season.name;document.querySelector('#strategy-board').innerHTML=cards.join('');
let alerts=[];state.products.filter(p=>p.stock<=5).forEach(p=>alerts.push(`<div class="alert"><strong>Reposição: ${esc(p.name)}</strong><small>Restam ${p.stock} unidades. Planeje a reposição antes de divulgar mais.</small></div>`));state.products.filter(p=>!state.sales.some(s=>s.productId===p.id)&&p.stock>5).slice(0,2).forEach(p=>alerts.push(`<div class="alert"><strong>Produto parado: ${esc(p.name)}</strong><small>${p.stock} unidades sem venda. Experimente combo, brinde ou conteúdo demonstrativo.</small></div>`));document.querySelector('#stock-alerts').innerHTML=alerts.length?alerts.join(''):'<p class="empty">Tudo bem por aqui: nenhum alerta importante no estoque.</p>';}
function renderProducts(){document.querySelector('#product-table').innerHTML=state.products.length?state.products.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.brand)}</td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${p.stock}${p.stock<=5?' <small>— baixo</small>':''}</td><td><button class="delete" data-delete="${p.id}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">Cadastre os produtos para começar.</td></tr>';document.querySelector('#sale-product').innerHTML=state.products.length?'<option value="">Selecione o produto</option>'+state.products.map(p=>`<option value="${p.id}">${esc(p.name)} (${p.stock} un.)</option>`).join(''):'<option>Cadastre um produto primeiro</option>';}
function renderSales(){let s=[...state.sales].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12);document.querySelector('#sales-table').innerHTML=s.length?s.map(x=>`<tr><td>${new Date(x.date+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${esc(product(x.productId)?.name||'Produto removido')}</td><td>${x.quantity}</td><td>${esc(x.channel)}</td><td>${esc(x.customer)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhuma venda registrada.</td></tr>';}
function renderReport(){let sales=filteredSales(), byChannel={},byCustomer={};sales.forEach(s=>{byChannel[s.channel]=(byChannel[s.channel]||0)+1;byCustomer[s.customer]=(byCustomer[s.customer]||0)+1});let items=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<li><span>${esc(k)}</span><strong>${v} venda${v!==1?'s':''}</strong></li>`).join('')||'<li>Nenhum dado no período.</li>';let ranked=aggregate(sales);document.querySelector('#report-content').innerHTML=`<article class="panel"><p class="eyebrow">CANAIS DE VENDA</p><h2>Onde o público compra</h2><ul class="report-list">${items(byChannel)}</ul></article><article class="panel"><p class="eyebrow">RELACIONAMENTO</p><h2>Perfil de cliente</h2><ul class="report-list">${items(byCustomer)}</ul></article><article class="panel"><p class="eyebrow">PREFERÊNCIAS</p><h2>Produtos procurados</h2><ul class="report-list">${ranked.slice(0,5).map(x=>`<li><span>${esc(x.p.name)}</span><strong>${x.q} un.</strong></li>`).join('')||'<li>Nenhuma venda no período.</li>'}</ul></article><article class="panel"><p class="eyebrow">PRÓXIMA AÇÃO</p><h2>Leitura para vender mais</h2><p class="muted">${ranked[0]?`Priorize ${esc(ranked[0].p.name)} nos canais que mais convertem e ofereça produtos complementares.`:'Registre vendas durante a semana. Em breve, este espaço mostrará padrões reais do seu público.'}</p></article>`;}
function render(){renderDashboard();renderProducts();renderSales();renderReport();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active');document.querySelector('#page-title').textContent=({dashboard:'Olá! Vamos cuidar das vendas.',products:'Organize seus produtos.',sales:'Cada venda conta.',report:'Entenda melhor seu público.'})[b.dataset.view]});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderDashboard();renderReport()});
document.querySelector('#show-product-form').onclick=()=>document.querySelector('#product-form').classList.toggle('hidden');document.querySelector('#product-form').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),newProduct={id:Date.now(),name:f.name,brand:f.brand,category:f.category,price:Number(f.price),stock:Number(f.stock)};state.products.push(newProduct);save();sheetRequest({acao:'produto',produto:newProduct});e.target.reset();e.target.classList.add('hidden');render()};document.querySelector('#product-table').onclick=e=>{if(e.target.dataset.delete){state.products=state.products.filter(p=>p.id!==Number(e.target.dataset.delete));save();render()}};
document.querySelector('#sale-date').value=today();document.querySelector('#sale-form').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),p=product(f.productId),q=Number(f.quantity);if(!p||p.stock<q)return alert('Verifique o produto e a quantidade em estoque.');let sale={id:Date.now(),productId:Number(f.productId),quantity:q,date:f.date,channel:f.channel,customer:f.customer};p.stock-=q;state.sales.push(sale);save();sheetRequest({acao:'venda',venda:sale});e.target.reset();document.querySelector('#sale-date').value=today();render()};
document.querySelector('#sample-data').onclick=sample;document.querySelector('#print-report').onclick=()=>window.print();document.querySelector('#csv-file').onchange=async e=>{let file=e.target.files[0];if(!file)return;let rows=(await file.text()).replace(/^\uFEFF/,'').trim().split(/\r?\n/),headers=rows.shift().split(/[;,]/).map(x=>x.trim().toLowerCase());let n=0;rows.forEach(row=>{let v=row.split(/[;,]/).map(x=>x.trim()),o=Object.fromEntries(headers.map((h,i)=>[h,v[i]])),p=state.products.find(x=>x.name.toLowerCase()===String(o.produto||'').toLowerCase()),q=Number(o.quantidade);if(p&&q>0&&p.stock>=q&&o.data){let sale={id:Date.now()+n,productId:p.id,quantity:q,date:o.data,channel:o.canal||'Outro',customer:o.cliente||'Cliente novo'};p.stock-=q;state.sales.push(sale);sheetRequest({acao:'venda',venda:sale});n++}});save();render();alert(`${n} venda(s) importada(s). Produtos não cadastrados ou sem estoque foram ignorados.`);e.target.value=''};render();sheetRequest();
